# Generated by Django 2.2.14 on 2020-08-17 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200817_0323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Readnum',
        ),
    ]
